name: xkcd_dbt_project
version: '1.0'
config-version: 2

profile: xkcd_dbt_profile

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  xkcd_dbt_project: 
    +packages:
      - dbt_utils
  staging:
    materialized: view
  marts:
    materialized: view
