services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: xkcd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  airflow-webserver:
    image: apache/airflow:2.6.1
    container_name: airflow_webserver
    build: .
    command: webserver
    entrypoint: /opt/airflow/init/entrypoint.sh
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/xkcd_db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-init:/opt/airflow/init
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.6.1
    container_name: airflow_scheduler
    build: .
    command: scheduler
    entrypoint: /opt/airflow/init/entrypoint.sh
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/xkcd_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-init:/opt/airflow/init
    depends_on:
      - postgres

volumes:
  postgres_data: